### PR TITLE
Remove some editor warnings and optimize project settings

### PR DESCRIPTION
**Pull request by Swarkin**
See individual commits for more info.

### CODE REVIEW

**Comment by MewPurPur** [comment]
Excellent! But... the `@warning_ignore` ones for integer divisions don't seem to be doing anything on my end? Is it the same for you?

**Comment by MewPurPur** [comment]
Anyway, merging, as this seems to be a Godot bug.

**Comment by MewPurPur** [comment]
Thanks!

**Comment by Swarkin** [comment]
> Excellent! But... the `@warning_ignore` ones for integer divisions don't seem to be doing anything on my end? Is it the same for you?

It seems to be a Godot bug but I included it anyways as it'll work once it gets fixed.

**Pull request merged**
