### PR TITLE
Add background color setting

### PR DESCRIPTION
**Pull request by Kiisu-Master**
@Vovkiv something happened with the ukrainian translation?

### CODE REVIEW

**Comment by Vovkiv** [comment]
I don't think so

**Comment by MewPurPur** [comment]
Is this ready for review?

**Comment by MewPurPur** [comment]
Check out https://github.com/MewPurPur/GodSVG/pull/690. I think the proper implementation of this would be not as a setting, but rather as a field inside a popup that contains other things relating to the background.

**Comment by MewPurPur** [comment]
Nevermind my last comment. Just rebase this and it can be merged.

**Comment by Kiisu-Master** [comment]
Ok

**Comment by Kiisu-Master** [comment]
If i update translation files now it will add other not related strings

**Comment by MewPurPur** [comment]
That's fine, it doesn't matter when updates are done.

**Comment by Kiisu-Master** [comment]
> That's fine, it doesn't matter when updates are done.

you just added merge conflicts

**Comment by MewPurPur** [comment]
Thanks!

**Pull request merged**
