### PR TITLE
Add Grey UI Buttons

### PR DESCRIPTION
**Pull request by Swarkin**
Adds grey UI Buttons that are more pleasant to look at in the Code Editor and Export Configuration.

image

image

### CODE REVIEW

**Comment by Swarkin** [comment]
Added:

image

**Comment by MewPurPur** [comment]
The "Cancel" and "Export" buttons should remain blue. OTOH this new theme should be applied to color_edit, color_field, enum_field, and number_field_with_slider.

**Comment by MewPurPur** [comment]
This gave me a different idea.

**Comment by MewPurPur** [comment]
Superseded by #231

**Pull request closed without merging**
