### PR TITLE
Working undoredo support

### PR DESCRIPTION
**Pull request by SeremTitus**
- #55 - Issue
- #104  - previous draft
Improved architecture from previous draft, **Fully Working**

A gizmo on the left Checkerboard area that pops and fades off  displaying name of the undo/redo action executed can be added

### CODE REVIEW

**Comment by MewPurPur** [comment]
I have an idea for where to implement History window, but I'd leave this for a later point.

**Comment by SeremTitus** [comment]
> I have an idea for where to implement History window, but I'd leave this for a later point.
> 
> Other than this, I'll check this out soon. From a cursory glance I like the code.

The idea sound good.

**Comment by MewPurPur** [comment]
My idea is: attribute edits are the only change that's sometimes granular, so we can have an undo_redo flag specifically for changing them, before the propagation flag.

**Comment by SeremTitus** [comment]
> * Moving a handle around saves its movements frame-by-frame. Instead, they should be saved to the history only when you release the handle. Same issue when dragging number sliders.
> * Undoing and redoing in the code editor doesn't work.
> 
> I found these issues in testing; they must be addressed before the PR can be merged.

I actually did not know the code editor was interractive , I though it only displayed...let me see how we can get that can also work

**Comment by SeremTitus** [comment]
> My idea is: attribute edits are the only change that's sometimes granular, so we can have an undo_redo flag specifically for changing them, before the propagation flag.

That will work

**Comment by SeremTitus** [comment]
> * Moving a handle around saves its movements frame-by-frame. Instead, they should be saved to the history only when you release the handle. Same issue when dragging number sliders.
> * Undoing and redoing from the code editor no longer works.
> 
> I found these issues in testing; they must be addressed before the PR can be merged.

@MewPurPur , all the tasks are done

**Comment by SeremTitus** [comment]
merge main to this has caused regression on the handles, let me see if I can fix that

**Comment by MewPurPur** [comment]
OK, ready for me to test it again?

I have to say the technical complexity and maintenance cost of this continues to concern me. I know UndoRedo tends to be complex, but I might still try to look into easier solutions myself before merging this.

**Comment by SeremTitus** [comment]
> OK, ready for me to test it again?
> 
> I have to say the technical complexity and maintenance cost of this continues to concern me. I know UndoRedo tends to be complex, but I might still try to look into easier solutions myself before merging this.

Yes , and to try to alleviate your concern on the complexity:
 ## General Overview:
 - Nothing has really changed in how they work 
 -  Added singleton UndoRedoManager
 -  In Attribute, Tag and TagSVG `duplicate` function was introduced
 - In TagB some function where improved others introduced but just same functions
 - In SVG functions that handle undoredo was added and signals conected to them
 - In SVG in order to support undoredo of code editor function `update_root_tag` was added which tries to match changes in code with existing attributes in the root_tag rather than just replacing it
 - In SVG , functions `deregester_from_undoredo` and `reregester_to_undoredo` (both take attributes) to deal with situations wher e a undoredo action should not be created . used by handle_manager and number_field_with_slider
 ## Signal that  Changed/Introduced:
- Pre-existing signals that where modifided sometime had more arguments hence had to undind them where ever they where existing connection
- In Attribute signal `change_details(old_value:Variant,new_value: Variant)` was introduced
- In TagB signal `child_tag_attribute_change_details` was introduced while `tag_added` , `tag_deleted` ,and function `connect_child_tag_signals()` was added dedicated to connect signals for child_tags
- In SVG signal `updated_root_tag` for cases that the root is update due to change in svg  string code (related to code editor) since function `update_root_tag` was introduced

On that note, I like to say I will be surprised if there can be a less complex and subtle implimentation. And I do encourage the pursuit  of an alternative.

**Comment by MewPurPur** [comment]
Would any part of this PR be useful in general? `update_root_tag()` sounds like it may be useful in more situations than just for UndoRedo, for example. Stuff like that can be extracted to make the review easier.

Please don't be annoyed by my scrutiny, I'm doing this because such features imply long-term responsibility and maintenance, even in the absence of the original contributor.

**Comment by SeremTitus** [comment]
> Would any part of this PR be useful in general? `update_root_tag()` sounds like it may be useful in more situations than just for UndoRedo, for example. Stuff like that can be extracted to make the review easier.
> 
> Please don't be annoyed by my scrutiny, I'm doing this because such features imply long-term responsibility and maintenance, even in the absence of the original contributor.

It is okay, I consider every part useful. update_root_tag() it is essential for this branch, but I can create a separate branch with only that change

**Comment by SeremTitus** [comment]
> Would any part of this PR be useful in general? `update_root_tag()` sounds like it may be useful in more situations than just for UndoRedo, for example. Stuff like that can be extracted to make the review easier.
> 
> Please don't be annoyed by my scrutiny, I'm doing this because such features imply long-term responsibility and maintenance, even in the absence of the original contributor.

- #137

**Comment by SeremTitus** [comment]
> Would any part of this PR be useful in general? `update_root_tag()` sounds like it may be useful in more situations than just for UndoRedo, for example. Stuff like that can be extracted to make the review easier.
> 
> Please don't be annoyed by my scrutiny, I'm doing this because such features imply long-term responsibility and maintenance, even in the absence of the original contributor.

removed any modifications to the function  `update_root_tag` still the code editor works ,I thought it was reliant on it turns out not

**Comment by SeremTitus** [comment]
> OK, ready for me to test it again?
> 
> I have to say the technical complexity and maintenance cost of this continues to concern me. I know UndoRedo tends to be complex, but I might still try to look into simpler solutions myself before merging this.

@MewPurPur I agree with the complexity , am going to turn it back to a draft an work on it gradually maybe eventualy it will get there... 
-  Currenty work everywhere even the code editor, not fully in the code editor
- Challenge that exist so far is any edits in the code editor generates new child_tags  of the root_tag hence any reference saved by undoRedo is lost

**Comment by MewPurPur** [comment]
Heya, why did you close this? Not interested in maintaining it anymore?

**Comment by SeremTitus** [comment]
> Heya, why did you close this? Not interested in maintaining it anymore?

@MewPurPur, currently I can not find a solution for intergrating the SVG code editor

**Pull request closed without merging**
