### PR TITLE
Implement move_tags_to in TagSVG

### PR DESCRIPTION
**Pull request by SeremTitus**
- prerequisite for features like drag and drop

### CODE REVIEW

**Comment by SeremTitus** [comment]
> If you want to take a shot at implementing this, you should use the `tags_moved_to` signal and make it work with the possibility of selecting multiple tags (e.g. with Ctrl+Click). You'd also need to have the Indications signleton listen for this signal and update those selections. This is why I left it for later, it's a really difficult task not just from a UI standpoint. I wouldn't try to tackle it until I have the UI to check various tricky scenarios with tag nesting, selections at different depths and and such, to make sure they all work.

am not sure if I completely understand you but  I have switched to `tags_moved_to`

**Comment by SeremTitus** [comment]
> If you want to take a shot at implementing this, you should use the `tags_moved_to` signal and make it work with the possibility of selecting multiple tags (e.g. with Ctrl+Click). You'd also need to have the Indications signleton listen for this signal and update those selections. This is why I left it for later, it's a really difficult task not just from a UI standpoint. I wouldn't try to tackle it until I have the UI to check various tricky scenarios with tag nesting, selections at different depths and and such, to make sure they all work.

ohh, allow multiple tags

**Comment by MewPurPur** [comment]
> You'd also need to have the Indications singleton listen for this signal and update those selections. This is why I left it for later, it's a really difficult task not just from a UI standpoint. I wouldn't try to tackle it until I have the UI to check various tricky scenarios with tag nesting, selections at different depths and and such, to make sure they all work.

You must still update `Indications.gd` to connect to this signal and update the selections. I'm also almost certain this won't work, for one, you don't take into consideration that a tag you're moving might have child tags, which should also have their Tag IDs updated, also you're using `add_tag()` which should only be used when you actually add tags.

**Comment by MewPurPur** [comment]
`<svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><g><g><circle cx="4" cy="4" r="1"/></g><circle cx="7" cy="8" r="1"/></g><circle cx="2.5" cy="12.5" r="1"/><circle cx="10.5" cy="2.5" r="1"/></svg>`

Basic example of a SVG with nesting that can be used for testing a UI.

**Comment by SeremTitus** [comment]
> > You'd also need to have the Indications singleton listen for this signal and update those selections. This is why I left it for later, it's a really difficult task not just from a UI standpoint. I wouldn't try to tackle it until I have the UI to check various tricky scenarios with tag nesting, selections at different depths and and such, to make sure they all work.
> 
> You must still update `Indications.gd` to connect to this signal and update the selections. I'm also almost certain this won't work, for one, you don't take into consideration that a tag you're moving might have child tags, which should also have their Tag IDs updated, also you're using `add_tag()` which should only be used when you actually add tags. You also need to take into consideration that if a tag and its child tag is selected, only the parent needs to move. Check out how this logic is implemented in the above functions.
> 
> this isn't really testable without some kind of UI that implements the ability to move tags

the tag child are considered since am pop the tag it self it will move with its children, am working on drag and drop currently and child tag move with there parent tag

**Comment by SeremTitus** [comment]
- implemented in #224

**Pull request closed without merging**
