### PR TITLE
Update godot version again and future proof version numbers stuff

### PR DESCRIPTION
**Pull request by Kiisu-Master**

### CODE REVIEW

**Comment by Kiisu-Master** [comment]
Can someone explain to me why in the windows export godot failed to create a connection to wayland but in linux export it just worked

**Comment by MewPurPur** [comment]
Not me, sorry.

**Comment by Kiisu-Master** [comment]
Why is it trying to use X11 or wayland at all. It should be using headless one...

**Comment by Kiisu-Master** [comment]
It's not my fault: godotengine/godot/issues/94755
Funny that one export failed and the other didn't.

**Comment by MewPurPur** [comment]
Fixed for Godot 4.3.rc2!

**Comment by Kiisu-Master** [comment]
Export seems to all work now. Downloaded windows export and it works fine too

**Comment by MewPurPur** [comment]
Thanks!

 /\\__/\\
(˶ᵔ ᵕ ᵔ˶)
/ > :heart:<\

**Pull request merged**
