### PR TITLE
Adding reversible zoom controls

### PR DESCRIPTION
**Pull request by AcridGdev**
I don't know how to move the files to the correct folders but  settings_menu.gd and viewport.gd replace the two with the same name in the src->ui parts folder

### CODE REVIEW

**Comment by MewPurPur** [comment]
Currently, this PR adds new files instead of modifying the existing ones, this should be fixed.

**Comment by AcridGdev** [comment]
> Currently, this PR adds new files instead of modifying the existing ones, this should be fixed.

I think I fixed it, tell em if I did not

**Comment by MewPurPur** [comment]
GlobalSettings.gd and settings_menu.gd still have the problem

**Comment by Kiisu-Master** [comment]
right now this would revert the middle mouse movement

**Comment by AcridGdev** [comment]
> GlobalSettings.gd and settings_menu.gd still have the problem

I fixed it so can you elaborate more

**Comment by MewPurPur** [comment]
Look at the "Files" tab, it says you're adding new files.

**Comment by MewPurPur** [comment]
Superseded by #162

**Pull request closed without merging**
