### PR TITLE
Extend export extension support

### PR DESCRIPTION
**Pull request by Qainguin**
Added .jpg and .webp extension support for exporting in web and native builds.

### CODE REVIEW

**Comment by Qainguin** [comment]
This should now be ready to merge.

**Comment by MewPurPur** [comment]
An initial implementation of exporting to these formats should also implement some kind of quality slider.

**Comment by Qainguin** [comment]
> An initial implementation of exporting to these formats should also implement some kind of quality slider.

I was thinking of just using the same scaler from the PNG.

**Comment by MewPurPur** [comment]
That's not a quality slider, it's for upscaling.

**Comment by Qainguin** [comment]
I just implemented that quality slider. It goes from 0.1 to 10 and then divides that number by 10.

**Comment by MewPurPur** [comment]
Good enough for an initial implementation :)

Thanks!

**Comment by Qainguin** [comment]
Can you decrease the font size of the quality label, I forgot to.

**Pull request merged**
