### PR TITLE
Small improvements to file opening.

### PR DESCRIPTION
**Pull request by Kiisu-Master**
- Adds drag and drop for files and file extension checks.
- Applies file extension checks and error messages when opening from cmdline
- makes all menus and dialogs extend `Dialog` and adds a `is_open `static variable to make sure that dropped files dont get opened when there is a dialog open.
- Moves opening SVG files to the SVG script

### CODE REVIEW

**Comment by MewPurPur** [comment]
Is this still WIP?

**Comment by Kiisu-Master** [comment]
It's working but..
Error message translations are missing and there is some code to deduplicate in the error system. Right now it's different checks that have the exact same code to create the popup, with the only difference being the error message.
Maybe something like this would be better?:
```gdscript
var error: String = ""
if invalid_svg_condition:
    error = "error message"
if not error.is_empty():
    # create error popup with error as text here
```

**Comment by MewPurPur** [comment]
It doesn't matter if translations are missing, obviously.

**Comment by MewPurPur** [comment]
Thanks!

**Pull request merged**
