### PR TITLE
actual hover using mouse_entered and mouse_exited control signals

### PR DESCRIPTION
**Pull request by SeremTitus**
godot 4.2.beta6 issues was fixed:
- https://github.com/godotengine/godot/pull/84547

### CODE REVIEW

**Comment by MewPurPur** [comment]
HYPE! I'll test this tomorrow, really hoping it will function entirely properly.

**Comment by MewPurPur** [comment]
Nice! I'll edit the PR slightly to resolve a conflict from my last PR and merge it right away.

**Comment by MewPurPur** [comment]
Thanks!

**Comment by SeremTitus** [comment]
> Nice! I'll edit the PR slightly to resolve a conflict from my last PR and merge it right away.

all good with me, should i make changes to the readme in this commit for the Godot version

**Comment by MewPurPur** [comment]
This PR seems to improve the performance of rebuilding the inspector by 5-10%. Cool!

**Pull request merged**
